source "https://rubygems.org"

gem "fastlane", ">= 2.203.1"  # Use the latest Fastlane version

# Use the latest version of Cocoapods
gem 'cocoapods'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)