# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do  


  desc "Submit a new Beta Build to AppCenter"
  lane :beta do
    gradle(task: "clean")

    package = load_json(json_path: "../package.json")
    gradle(
      task: "assemble",
      flavor: "beta",
      print_command: true,
      build_type: "Release",
      properties: {
        "versionName" => package["version"],
        "versionCode" => number_of_commits
      }
    )
    changelog = changelog_from_git_commits(commits_count: 1)
    
    appcenter_upload(
      api_token: ENV['APPCENTER_TOKEN'],
      owner_name: "moonlet",
      app_name: "Moonlet-Beta",
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
      release_notes: changelog,
      notify_testers: true
    )
  end

  lane :deploy do
    gradle(task: "clean")

    package = load_json(json_path: "../package.json")
    gradle(
      task: "bundle",
      flavor: "stable",
      build_type: "Release"
      properties: {
        "versionName" => package["version"],
        "versionCode" => number_of_commits
      }
    )
    # changelog = changelog_from_git_commits(commits_count: 1)
    
    upload_to_play_store(
      track: "alpha", 
      validate_only: false,
      json_key: 'app/moonlet-playstore-key/key.json'
    );
  end

end
