name: Detox iOS

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 120

    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1

    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Generate firebase config file
        run: |
          echo '${{ secrets.FB_CONFIG_IOS_BETA }}' > ios/GoogleService-Info.plist
          echo '${{ secrets.FB_CONFIG_WEB_BETA }}' > src/config/firebase-web-beta.ts
          echo '${{ secrets.FB_CONFIG_WEB_DEPLOY }}' > src/config/firebase-web-release.ts

    - name: NPM install
      run: npm i

    - name: Cache Pods
      uses: actions/cache@v1
      id: podcache
      with:
        path: ios/Pods
        key: pods-${{ hashFiles('**/Podfile.lock') }}

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        cd ios && pod install && cd ..

    - name: Install wix/brew
      run: brew tap wix/brew

    - name: Install applesimutils
      run: brew install applesimutils

    - name: Generate Icon
      run: npm run generate-icons

    - name: Detox Build iOS
      run: npm run ios
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        KEYCHAIN_TOKEN: ${{ secrets.KEYCHAIN_TOKEN }}
        NODE_ENV: production

    - name: Detox Test iOS
      run: npm run detox:test:ios
