name: Detox

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 120

    env:
      DEVELOPER_DIR: /Applications/Xcode_11.2.app
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master

    - name: Cache node modules
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Cache Pods
      uses: actions/cache@v1
      id: podcache
      with:
        path: ios/Pods
        key: pods-${{ hashFiles('**/Podfile.lock') }}

    - name: Update Pods
      run: |
        gem update cocoapods xcodeproj
        cd ios && pod install && cd ..
    - run: brew tap wix/brew
    - run: brew install applesimutils
    - run: npm run detox:build:ios
    - run: npm run detox:test:ios
