on: push
name: Deploy Beta iOS and Android
jobs:
  # beta-android:
  #   name: Beta Release Android
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: "10.x"
  #     - name: Dependencies install
  #       run: bundle install
  #     - name: NPM install
  #       run: npm i
  #     - name: Gety sign ssh-keys
  #       run: git clone git@gitlab.com:moonlet/moonlet-playstore-key.git .
  #       env:
  #         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  beta-ios:
    name: Beta Release iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - uses: actions/checkout@v1
      - name: Setup key
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_CERTS }}
      - name: Add to host
        run: ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      - name: Checkout
        uses: actions/checkout@master
      - name: Dependencies install
        run: cd ios && bundle install
      - name: NPM install
        run: npm i
      - name: Cocoapods install
        run: cd ios && pod install
      - name: Run fastlane beta
        run: xcversion select 11.1 && cd ios/fastlane && fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
