on: push
name: Deploy Beta iOS
jobs:
  test:
    name: Beta iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup key
           uses: webfactory/ssh-agent@v0.1.1
           with:
                ssh-private-key: ${{ secrets.SSH_CERTS }}
      - run: |
                ssh-add -l
                echo SSH_AUTH_SOCK is at $SSH_AUTH_SOCK
      - name: Checkout
        uses: actions/checkout@master
      - name: Dependencies install
        run: cd ios && bundle install

      - name: Run fastlane beta
        run: cd ios/fastlane && bundle exec fastlane beta --verbose
   