on: push
name: Deploy Beta iOS
jobs:
  test:
    name: Beta iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        run: actions/checkout@master
          - uses: webfactory/ssh-agent@v0.1.1
              with:
                ssh-private-key: ${{ secrets.SSH_CERTS }}
      - name: Dependencies install
        run: cd ios && bundle install

      - name: Run fastlane beta
        run: cd ios/fastlane && bundle exec fastlane beta --verbose
   