on: push
name: Deploy Beta iOS
jobs:
  test:
    name: Beta iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Hello world
        with: MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: echo Hello world $MATCH_PASSWORD $middle_name 
      - name: Bundle install
        run: cd ios && bundle install
      - name: Run fastlane beta
        run: cd ios/fastlane && bundle exec fastlane beta