on: push
name: Deploy Beta iOS
jobs:
  test:
    name: Beta iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Bundle install
        run: cd ios && bundle install
      - name: Run fastlane beta
        env: 
          MATCH_PASSWORD: TN49qUTz[B
          FASTLANE_PASSWORD: wivwaf-zymxo6-rIvbim
        run: cd ios/fastlane && bundle exec fastlane beta