on: push
name: Deploy Beta iOS
jobs:
  test:
    name: Beta iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
      - name: Hello world
        run: echo Hello world $MATCH_PASSWORD $middle_name $FASTLANE_PASSWORD!
      - name: Bundle install
        run: cd ios && bundle install
      - name: Run fastlane beta
        run: cd ios/fastlane && bundle exec fastlane beta