on: push
name: Deploy Beta iOS
jobs:
  test:
    name: Beta iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup key
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.SSH_CERTS }}
      - name: Add to host
        run: ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      - name: Checkout
        uses: actions/checkout@master
      - name: Dependencies install
        run: cd ios && bundle install
      - name: Run fastlane beta
        uses: cd ios/fastlane && bundle exec fastlane beta --verbose
        with:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
