on: push
name: Deploy Beta iOS
jobs:
  test:
    name: Beta iOS
    runs-on: macOS-latest
    steps:
      - name: Set ssh key
      - uses: webfactory/ssh-agent@v0.1.1
        with:
        ssh-private-key: ${{ secrets.SSH_CERTS }}
      - name: Checkout
        uses: actions/checkout@master
      - name: Dependencies install
        run: cd ios && bundle install

      - name: Run fastlane beta
        run: cd ios/fastlane && bundle exec fastlane beta --verbose
   