on: push
name: Deploy Beta iOS
jobs:
  test:
    name: Beta iOS
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Bundle install
        run: cd ios && bundle install
      - name: Run fastlane beta
        env: 
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
        run: echo Hello world $MATCH_PASSWORD $FASTLANE_PASSWORD
   