name: Admin Deployment

# Controls when the workflow will run
on:
  workflow_dispatch:

env:
  MATCH_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}


jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "TEST"
          echo "MATCH_PASSWORD=$MATCH_PASSWORD" > asd.env

      - name: Save as artifact
        uses: actions/upload-artifact@v3
        with:
          name: asd.env
          path: asd.env
