name: Admin Deployment

on:
  workflow_dispatch:

env:
  # MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
  MATCH_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}


jobs:
  build:
    name: test
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "TEST"
          echo "MATCH_PASSWORD=$MATCH_PASSWORD" > asd.env

      - name: Save as artifact
        uses: actions/upload-artifact@v4
        with:
          name: asd.env
          path: asd.env
